import React , {useState, useEffect} from 'react'
import  {Cards , Loader , FormField} from "../Components"
const Home = () => {
  const [Loading , setLoading ] = useState(false)
  const [searchText, setsearchText] = useState("")
  const [allPosts , setallPosts] = useState([])

  useEffect(()=>{
    (async function fetchdata(){
      try {
        setLoading(true)
        const Postsdata = await fetch('http://localhost:8000/api/v1/post',
        {
          method : "GET",
          headers : {
          'Content-Type' : 'application/json',
          },
        })
        const Posts = await Postsdata.json()
        setallPosts(Posts.data)
      } catch (error) {
        alert("Error Loading Posts"+ error)
      }finally{
        setLoading(false)
      }
    })()
  },[])

  const RenderBody = ({data, title}) => {
    if(data.length > 0){
      return data.map(post => <Cards key={post._id} Posts = {post}/>)
    }
    return(
      <h2 className='mt-5 font-bold text-[#6339ff] text-xl uppercase'>
        {title}
      </h2>
    )
  }
  return (
    <section className='max-w-7xl mx-auto'>
      <div>
        <h1 className='font-extrabold text-black text-[2rem]'>The Community Gallery</h1>
        <p className='mt-2 text-[#666e75] text-[1rem] max-w-[500px]'>Browse thrugh the collection of some awesome artworks generated by Dall - E AI</p>
      </div>
      <div  className='mt-[1rem]'>
        <FormField />
      </div>
      <div  className='mt-[1rem]'>
        {
          Loading ? <Loader /> :
          <>
            {
              searchText && 
              <h2 className='font-medium text-[#666e75] text-xl mb-3'>
                Showing results for <span className='text-black'>{searchText}</span>
              </h2>
            }
            <div className='grid lg:grid-cols-4 sm:grid-cols-3 xs:grid-cols-2 grid-cols-1 gap-3'>
              {
                searchText ? 
                  <RenderBody 
                    data = {[]}
                    title = "No Search Results Found"
                  /> :
                  <RenderBody 
                    data = {allPosts}
                    title="No Posts Found"
                  />
              }
            </div>
          </>
        }
      </div>
    </section>
  )
}

export default Home